version: '2.3'

services:
  elasticsearch:
    container_name: elk-es
    image: elasticsearch:7.0.1
    ports:
      - "9250:9200"
      - "9350:9300"
    restart: always
    volumes:
      - ./elastichsearch/data:/usr/share/elasticsearch/data
    environment: 
      - discovery.type=single-node
    networks:
      - my-netwk

  kibana:
    container_name: kibana
    image: kibana:7.0.1
    ports:
      - "5601:5601"
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200 
    networks:
      - my-netwk
    depends_on:
      - elasticsearch
        # condition: service_healthy

  logstash:
    container_name: logstash
    image: logstash:7.0.1
    restart: always
    ports:
      - "3200:3200"
      - "9600:9600"
    build:
      context: logstash/
    volumes: 
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - my-netwk

networks:
  my-netwk:
    driver: bridge